// Letters instead of the old Drupal forms: mailto with a subject and a body template (only the published addresses).
const libraryMail='tara_libraru79@mail.ru';
const referenceMail='spravkatara@mail.ru';
const mailtoHref=(subject,lines,to=libraryMail)=>'mailto:'+to+'?subject='+encodeURIComponent(subject)+'&amp;body='+encodeURIComponent(lines.join('\r\n')+'\r\n');
const sprite=(name,cls)=>`<svg${cls?` class="${cls}"`:''} aria-hidden="true" focusable="false"><use href="#i-${name}"/></svg>`;
// Service tile: bright icon square, title, line, arrow knob (colour: t-sun, t-rowan, t-teal, t-sky; is-big is navy)
const svcTile=(href,cls,ic,title,line)=>`<a class="svc-tile ${cls}" href="${href}"><span class="svc-ic">${sprite(ic)}</span><span class="svc-go">${sprite('arrow')}</span><span class="svc-text"><strong>${title}</strong><small>${line}</small></span></a>`;
// «Детям» (/detyam/): the hub and three interactive pages. Their behaviour is in site/kids.js (loaded only there by app.js);
// the markup below is what a reader sees without JavaScript. Data: site/data/chto-pochitat.json, viktorina.json, znachki.json (docs/DETYAM.md).
const kidsImg=(base,widths,w,h,sizes,alt='')=>`<picture><source type="image/avif" srcset="${widths.map(n=>`${base}-${n}.avif ${n}w`).join(', ')}" sizes="${sizes}"><img src="${base}-${widths.at(-1)}.webp" srcset="${widths.map(n=>`${base}-${n}.webp ${n}w`).join(', ')}" sizes="${sizes}" width="${w}" height="${h}" alt="${alt}" loading="lazy" decoding="async"></picture>`;
const kidsTile=(href,tone,art,title,line,extra='')=>`<a class="kids-tile ${tone}" href="${href}"><span class="kids-tile-art" aria-hidden="true">${art}</span><span class="kids-tile-text"><strong>${title}</strong><small>${line}</small>${extra}</span><span class="svc-go" aria-hidden="true">${sprite('arrow')}</span></a>`;
const kidsNoJs=what=>`<p class="kids-nojs">${what} работает, когда в браузере включён JavaScript. Если не получается, спросите библиотекаря: <a href="tel:+73817122020">+7 (38171) 2-20-20</a> (детская библиотека).</p>`;
window.libraryContent = {
 firstvisit:{title:'Первый раз в библиотеке',html:`<p class="page-intro">Возьмите паспорт, выберите удобную библиотеку и приходите за своей следующей книгой.</p><div class="facts-row"><div><strong>5 книг</strong><span>можно взять за один раз</span></div><div><strong>15 дней</strong><span>обычный срок выдачи книг</span></div><div><strong>7 дней</strong><span>для периодических изданий</span></div></div><h2>Как записаться</h2><div class="steps"><div><span>01</span><h3>Возьмите документ</h3><p>Для записи нужен паспорт с отметкой о регистрации. Без постоянной регистрации доступны читальные залы и выдача под залог.</p></div><div><span>02</span><h3>Приходите в библиотеку</h3><p>Центральная библиотека находится в Таре на ул. Александровской, 58. Можно выбрать и ближайший филиал.</p></div><div><span>03</span><h3>Выберите книги</h3><p>Библиотекарь поможет найти издание и объяснит правила пользования.</p></div></div><a class="button dark" href="/?page=libraries">Адреса библиотек</a><h2>Частые вопросы</h2><div class="faq"><details><summary>Как записать ребёнка до 14 лет?</summary><p>Нужен документ родителя или законного представителя и поручительство. Бланк выдаст библиотекарь.</p></details><details><summary>Можно ли продлить книгу?</summary><p>Да, до двух раз подряд, если издание не востребовано другими читателями и нет задолженности. <a href="/?page=renew">Условия продления</a>.</p></details><details><summary>Можно прийти со своим ноутбуком?</summary><p>Да, в читальном зале можно работать на своём ноутбуке без звуковых сигналов. В библиотеках доступны интернет и Wi-Fi.</p></details><details><summary>Что делать, если нужной книги нет?</summary><p>Обратитесь к библиотекарю. Он проверит каталоги и подскажет возможность заказа из другой библиотеки.</p></details></div><p class="source-note"><a href="https://taralib.ru/sites/default/files/pravila_polzovaniya_crb.pdf">Правила пользования · PDF</a> · <a href="https://taralib.ru/content/pamyatka-chitatelyu">Полная памятка читателя</a></p>`},
 renew:{title:'Продлить книгу',html:`<p class="page-intro">Нужно ещё немного времени? Напишите в библиотеку или позвоните.</p><div class="action-panel"><div><h2>Ещё 14 дней на чтение</h2><p>Продление возможно до двух раз подряд, если на книгу нет спроса и у читателя нет задолженности.</p><div class="hero-actions"><a class="button dark" href="${mailtoHref('Продление книг',['ФИО: ','Номер читательского билета: ','Какие книги продлить (автор, название): ','Телефон для связи: '])}">Написать письмо</a><a class="button outline" href="tel:+73817121242">Позвонить</a></div><p class="mail-copy">Адрес для писем: <strong>${libraryMail}</strong>, тема «Продление книг».<br>Телефон: <a href="tel:+73817121242">+7 (38171) 2-12-42</a></p><small>Кнопка откроет почтовую программу с готовым письмом. Если она не открылась, скопируйте адрес и напишите с любой почты.</small></div></div><h2>Как это работает</h2><div class="steps"><div><span>01</span><h3>Напишите письмо</h3><p>Укажите ФИО, номер читательского билета, автора и название книг и телефон для связи.</p></div><div><span>02</span><h3>Дождитесь ответа</h3><p>Библиотека рассматривает заявку в течение суток. Письмо, отправленное в нерабочее время, выполнят на следующий день, в выходной — в первый рабочий день.</p></div><div><span>03</span><h3>Проверьте новую дату</h3><p>Срок считается продлённым только после подтверждения библиотеки по электронной почте или телефону.</p></div></div>`},
 delivery:{title:'Книги на дом',html:`<p class="page-intro">Если вы или ваши близкие не можете самостоятельно прийти в библиотеку, книги можно получать дома.</p><div class="action-panel"><div><h2>Доставка бесплатно</h2><p>Библиотека доставляет книги по месту жительства читателя. Условия и возможность обслуживания по вашему адресу уточните по телефону.</p><a class="button dark" href="tel:+73817121242">+7 (38171) 2-12-42</a><small>Справки и запись: Олеся Ивановна Брага.</small></div></div><h2>Перед звонком</h2><p>Подготовьте адрес и расскажите, какие книги вам интересны. Сотрудник объяснит порядок записи и согласует обслуживание.</p><p><a class="text-link" href="https://taralib.ru/sites/default/files/polozhenie_o_knige_na_dom.pdf">Положение об услуге · PDF</a></p>`},
 documents:{title:'Электронная доставка документов',html:`<p class="page-intro">Получите копию статьи или небольшого фрагмента книги из фондов библиотек.</p><div class="facts-row"><div><strong>До 10 страниц</strong><span>в одном заказе</span></div><div><strong>По e-mail</strong><span>или в библиотеке</span></div><div><strong>Платная услуга</strong><span>по прейскуранту исполнителя</span></div></div><h2>Как заказать</h2><p>Обратитесь в свою библиотеку. Укажите автора, название издания, год и нужные страницы. Для каждого источника оформляется отдельный заказ.</p><p>Если издания нет в фонде Тарской библиотечной системы, по вашему желанию запрос направят в Омскую библиотеку имени А. С. Пушкина.</p><div class="hero-actions"><a class="button dark" href="/?page=contacts">Контакты библиотеки</a><a class="button outline" href="/?page=libraries">Найти филиал</a></div><p class="source-note">Стоимость уточняется до получения копий. Материалы предназначены для личного использования с соблюдением авторских прав.</p>`},
 ask:{title:'Спросить библиотекаря',html:`<p class="page-intro">Поможем найти книгу, подобрать литературу по теме и разобраться в библиотечных услугах.</p><div class="contact-cards"><section class="contact-card cc-phone"><span class="cc-ic">${sprite('phone')}</span><div class="cc-body"><h2>По телефону</h2><p class="cc-big">+7 (38171) 2-12-42</p><p>Быстрый вопрос в часы работы библиотеки.</p><a class="button btn-teal" href="tel:+73817121242">Позвонить ${sprite('arrow')}</a></div></section><section class="contact-card cc-mail"><span class="cc-ic">${sprite('mail')}</span><div class="cc-body"><h2>Письменно</h2><p class="cc-big">${referenceMail}</p><p>Справочно-библиографическая служба. В теме письма напишите «Вопрос библиотекарю», а в тексте — что уже знаете по теме.</p><a class="button btn-rowan" href="${mailtoHref('Вопрос библиотекарю',['Ваш вопрос: ','Как с вами связаться: '],referenceMail)}">Написать письмо ${sprite('arrow')}</a></div></section></div><h2>Нужен ответ об услугах?</h2><div class="resource-list"><a href="/?page=firstvisit">${sprite('card','ri')}<strong>Как стать читателем</strong></a><a href="/?page=renew">${sprite('renew','ri')}<strong>Как продлить книгу</strong></a><a href="/?page=delivery">${sprite('home','ri')}<strong>Доставка книг на дом</strong></a><a href="/?page=documents">${sprite('file','ri')}<strong>Заказать копию документа</strong></a></div>`},
 services:{title:'Читателям',html:`<p class="page-intro">От первой книги до работы с архивами. Выберите задачу, а мы подскажем следующий шаг.</p><div class="svc-bento">${svcTile('/?page=catalog','is-big','search','Найти книгу','Электронный каталог библиотек Омской области')}${svcTile('/?page=firstvisit','t-rowan','card','Записаться в библиотеку','Документы, сроки выдачи и ответы на вопросы')}${svcTile('/?page=renew','t-teal','renew','Продлить книгу','По электронной почте или по телефону')}${svcTile('/?page=delivery','t-sky','home','Книги на дом','Бесплатное обслуживание на дому')}${svcTile('/?page=documents','t-sun','file','Получить копию документа','Статьи и фрагменты книг')}${svcTile('/?page=ask','t-teal is-wide','question','Спросить библиотекаря','Помощь с поиском и подбором литературы')}</div><h2>Другие возможности</h2><p>В библиотеке можно работать со своим ноутбуком, пользоваться интернетом и справочными ресурсами.</p><a class="text-link" href="https://taralib.ru/content/uslugi">Все услуги учреждения</a>`},
 kids:{title:'Детям',docTitle:'Детям: книги, викторины и значки',html:`<p class="page-intro">Подберём книгу по возрасту, проверим знания в викторине и соберём значки читателя.</p><div class="kids-greet"><div class="kids-owl" data-kids-owl aria-hidden="true"></div><p class="kids-bubble">Привет! Я сова-проводник. С чего начнём?</p></div><div class="kids-tiles">${kidsTile('/?page=kids-books','t-sun',kidsImg('/assets/genres/priklyucheniya',[160,320],360,320,'(max-width: 600px) 96px, 150px'),'Что почитать?','Книги по возрасту и жанру из списков нашей детской библиотеки')}${kidsTile('/?page=kids-quiz','t-sky',kidsImg('/assets/mascot/think',[240,480],363,480,'(max-width: 600px) 80px, 120px'),'Литературная викторина','Сказки, приключения, классика и родная Тара')}${kidsTile('/?page=kids-badges','t-rowan',kidsImg('/assets/badges/kniga-zvezda',[96,192],192,192,'(max-width: 600px) 80px, 120px'),'Значки читателя','Восемь значков за викторины, книги и походы в библиотеку','<span class="kids-chip" data-kids-count hidden></span>')}${kidsTile('/?page=libraries','t-teal',kidsImg('/assets/badges/karta',[96,192],192,192,'(max-width: 600px) 80px, 120px'),'Библиотека рядом с домом','Адреса библиотек в Таре и сёлах района')}</div><h2>Детская библиотека</h2><p>Центральная районная детская библиотека: Тара, ул. Александровская, 58. <a href="tel:+73817122020">+7 (38171) 2-20-20</a>.</p><p>Пн–пт: 09:00–18:00. Вс: 10:00–17:00. Сб: выходной.</p><p><a class="text-link" href="http://www.dbibtara.ru/" target="_blank" rel="noopener">Сайт детской библиотеки</a></p>`},
 'kids-books':{title:'Что почитать?',crumbs:[{label:'Детям',href:'/?page=kids'}],html:`<p class="page-intro">Выберите возраст и жанр — сова покажет книги из рекомендательных списков нашей детской библиотеки.</p><div class="kids-app" data-kids="books">${kidsNoJs('Подбор книг')}</div>`},
 'kids-quiz':{title:'Литературная викторина',crumbs:[{label:'Детям',href:'/?page=kids'}],html:`<p class="page-intro">Один вопрос за раз, три или четыре ответа. Сова подскажет, угадали ли вы.</p><div class="kids-app" data-kids="quiz">${kidsNoJs('Викторина')}</div>`},
 'kids-badges':{title:'Значки читателя',crumbs:[{label:'Детям',href:'/?page=kids'}],html:`<p class="page-intro">Значки появляются сами, когда вы проходите викторины, подбираете книги и приходите в библиотеку. Они хранятся только на этом устройстве.</p><div class="kids-app" data-kids="badges">${kidsNoJs('Коллекция значков')}</div>`}
};
